### ISSUE TITLE
 Sorry, I don't understand what this package is trying to do?

### ISSUE THREAD

**Issue by baokeyu123** [Blackman99/create#23]
Hello Blackman,

Hope you're doing well.
If you want others to use it, you'd better improve your readme or documentation.

Thanks,
KB

**Comment by Blackman99** [comment]
Hi KB,

Thanks for your caring. Hope you the same

This is the template project for creating new javascript projects with minimal presets like:
* eslint for code examination
* vitest for unit test
* unbuild for packing  

And this repo would make sure to keep them up to date with an auto check github action

Let's say if I want to start a new javascript project and will publish it later to npm. 
For example, an UI library or a javascript utility functions library. 
Code linter, unit test, packing should be the basic things. And If I want to create more projects. These things will still be required.

So I create this project to help myself or any other people who might have the same trouble save some time when creating a new project

**Comment by baokeyu123** [comment]
Hi DS,

Thanks for your reply.
I see what you mean. Please continue to keep updated and keep doing meaningful things.
